name: jstam
favicon: null
layout_spectrum: 0.25976
typography_spectrum: 0.57702
title: 'JStam : John Stammerman'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0b06'
    - '#ffffff'
    - '#dac6a1'
    - '#a46e26'
    - '#f32e37'
  brandStrength: 0.8125
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
