layout_spectrum: 0.9346276391297579
typography_spectrum: 0.3487158571369946
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.48231514589861035
  lightness: 0.23654085909947753
  saturation: 0.7052957296837121
  rhythmicContrast: 0.47528446186333895
name: jstam
favicon: null
title: 'JStam : John Stammerman'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
